
const digitalList = [
    {id:1 , title:"گوشی همراه" , path:"/" , className:"category-link" , dataId : 1},
    {id:2 , title:"سامسونگ" , path:"/" , className:"sub-category-link" , dataParentId : 1},
    {id:3 , title:"هواوی" , path:"/" , className:"sub-category-link" , dataParentId : 1},
    {id:4 , title:"اپل" , path:"/" , className:"sub-category-link" , dataParentId : 1 },
    {id:5 , title:"شیائومی" , path:"/" , className:"sub-category-link" , dataParentId : 1},
    {id:6 , title:"لوازم جانبی گوشی" , path:"/" , className:"category-link" , dataId : 2},
    {id:7 , title:"کیف" , path:"/" , className:"sub-category-link", dataParentId : 2},
    {id:8 , title:"کاور" , path:"/" , className:"sub-category-link", dataParentId : 2},
    {id:9 , title:"قاب" , path:"/" , className:"sub-category-link", dataParentId : 2},
    {id:10 , title:"کالای دیجیتال" , path:"/" , className:"category-link" ,dataId:3},
    {id:11 , title:"کالای دیجیتال" , path:"/" , className:"category-link" , dataId:4},
    {id:12 , title:"کالای دیجیتال" , path:"/" , className:"sub-category-link" , dataParentId:4},
    {id:13 , title:"کالای دیجیتال" , path:"/" , className:"sub-category-link", dataParentId:4},
    {id:14 , title:"کالای دیجیتال" , path:"/" , className:"sub-category-link", dataParentId:4},
    {id:15 , title:"کالای دیجیتال" , path:"/" , className:"category-link", dataId:5},
    {id:16 , title:"کالای دیجیتال" , path:"/" , className:"category-link", dataId:6},
    {id:17 , title:"کالای دیجیتال" , path:"/" , className:"category-link", dataId:7},
    {id:18 , title:"کالای دیجیتال" , path:"/" , className:"sub-category-link", dataParentId:7},
    {id:19 , title:"کالای دیجیتال" , path:"/" , className:"category-link", dataId:8},
    {id:20 , title:"کالای دیجیتال" , path:"/" , className:"category-link", dataId:9},
    {id:21 , title:"کالای دیجیتال" , path:"/" , className:"category-link", dataId:10},
    {id:22 , title:"کالای دیجیتال" , path:"/" , className:"category-link", dataId:11},
    {id:23 , title:"کالای دیجیتال" , path:"/" , className:"category-link", dataId:12},
    {id:24 , title:"کالای دیجیتال" , path:"/" , className:"sub-category-link", dataParentId:12},
    {id:25 , title:"کالای دیجیتال" , path:"/" , className:"sub-category-link", dataParentId:12},
    {id:26 , title:"کالای دیجیتال" , path:"/" , className:"sub-category-link", dataParentId:12},
    {id:27 , title:"کالای دیجیتال" , path:"/" , className:"sub-category-link", dataParentId:12},
    {id:28 , title:"کالای دیجیتال" , path:"/" , className:"category-link", dataId:13},
    {id:29 , title:"کالای دیجیتال" , path:"/" , className:"category-link", dataId:14},
    {id:30 , title:"کالای دیجیتال" , path:"/" , className:"category-link", dataId:15},
]

export default digitalList ;