const Lists = [
    {id:1 , title:"گوشی همراه" , path:"/" , className:"category-link"},
    {id:2 , title:"سامسونگ" , path:"/" , className:"sub-category-link"},
    {id:3 , title:"هواوی" , path:"/" , className:"sub-category-link"},
    {id:4 , title:"اپل" , path:"/" , className:"sub-category-link"},
    {id:5 , title:"شیائومی" , path:"/" , className:"sub-category-link"},
    {id:6 , title:"لوازم جانبی گوشی" , path:"/" , className:"category-link"},
    {id:7 , title:"کیف" , path:"/" , className:"sub-category-link"},
    {id:8 , title:"کاور" , path:"/" , className:"sub-category-link"},
    {id:9 , title:"قاب" , path:"/" , className:"sub-category-link"},
    {id:10 , title:"کالای دیجیتال" , path:"/" , className:"category-link"},
    {id:11 , title:"کالای دیجیتال" , path:"/" , className:"category-link"},
    {id:12 , title:"کالای دیجیتال" , path:"/" , className:"sub-category-link"},
    {id:13 , title:"کالای دیجیتال" , path:"/" , className:"sub-category-link"},
    {id:14 , title:"کالای دیجیتال" , path:"/" , className:"sub-category-link"},
    {id:15 , title:"کالای دیجیتال" , path:"/" , className:"category-link"},
    {id:16 , title:"کالای دیجیتال" , path:"/" , className:"category-link"},
    {id:17 , title:"کالای دیجیتال" , path:"/" , className:"category-link"},
    {id:18 , title:"کالای دیجیتال" , path:"/" , className:"sub-category-link"},
    {id:19 , title:"کالای دیجیتال" , path:"/" , className:"category-link"},
    {id:20 , title:"کالای دیجیتال" , path:"/" , className:"category-link"},
    {id:21 , title:"کالای دیجیتال" , path:"/" , className:"category-link"},
    {id:22 , title:"کالای دیجیتال" , path:"/" , className:"category-link"},
    {id:23 , title:"کالای دیجیتال" , path:"/" , className:"category-link"},
    {id:24 , title:"کالای دیجیتال" , path:"/" , className:"sub-category-link"},
    {id:25 , title:"کالای دیجیتال" , path:"/" , className:"sub-category-link"},
    {id:26 , title:"کالای دیجیتال" , path:"/" , className:"sub-category-link"},
    {id:27 , title:"کالای دیجیتال" , path:"/" , className:"sub-category-link"},
    {id:28 , title:"کالای دیجیتال" , path:"/" , className:"category-link"},
    {id:29 , title:"کالای دیجیتال" , path:"/" , className:"category-link"},
    {id:30 , title:"کالای دیجیتال" , path:"/" , className:"category-link"},
]

export default Lists ;
