const Lists = [
    {id:1 , title:"کالای تست" , path:"/" , className:"category-link"},
    {id:2 , title:"کالای تست" , path:"/" , className:"sub-category-link"},
    {id:3 , title:"کالای تست" , path:"/" , className:"sub-category-link"},
    {id:4 , title:"کالای تست" , path:"/" , className:"sub-category-link"},
    {id:5 , title:"کالای تست" , path:"/" , className:"sub-category-link"},
    {id:6 , title:"کالای تست" , path:"/" , className:"category-link"},
    {id:7 , title:"کالای تست" , path:"/" , className:"sub-category-link"},
    {id:8 , title:"کالای تست" , path:"/" , className:"sub-category-link"},
    {id:9 , title:"کالای تست" , path:"/" , className:"sub-category-link"},
    {id:10 , title:"کالای تست" , path:"/" , className:"category-link"},
    {id:11 , title:"کالای تست" , path:"/" , className:"category-link"},
    {id:12 , title:"کالای تست" , path:"/" , className:"sub-category-link"},
    {id:13 , title:"کالای تست" , path:"/" , className:"sub-category-link"},
    {id:14 , title:"کالای تست" , path:"/" , className:"sub-category-link"},
    {id:15 , title:"کالای تست" , path:"/" , className:"category-link"},
    {id:16 , title:"کالای تست" , path:"/" , className:"category-link"},
    {id:17 , title:"کالای تست" , path:"/" , className:"category-link"},
    {id:18 , title:"کالای تست" , path:"/" , className:"sub-category-link"},
    {id:19 , title:"کالای تست" , path:"/" , className:"category-link"},
    {id:20 , title:"کالای تست" , path:"/" , className:"category-link"},
    {id:21 , title:"کالای تست" , path:"/" , className:"category-link"},
    {id:22 , title:"کالای تست" , path:"/" , className:"category-link"},
    {id:23 , title:"کالای تست" , path:"/" , className:"category-link"},
    {id:24 , title:"کالای تست" , path:"/" , className:"sub-category-link"},
    {id:25 , title:"کالای تست" , path:"/" , className:"sub-category-link"},
    {id:26 , title:"کالای تست" , path:"/" , className:"sub-category-link"},
    {id:27 , title:"کالای تست" , path:"/" , className:"sub-category-link"},
    {id:28 , title:"کالای تست" , path:"/" , className:"category-link"},
    {id:29 , title:"کالای تست" , path:"/" , className:"category-link"},
    {id:30 , title:"کالای تست" , path:"/" , className:"category-link"},
]

export default Lists ;